name: Check

on: [workflow_dispatch, push]

jobs:

  # Check

  compile:

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        test: [ button, reed-switch, temperature-sensor ]

    runs-on: ${{ matrix.os }}
  
    steps:

      # Clone repository
      
      - name: Clone repository
        uses: actions/checkout@main

      # Check if this tester changes

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@main

      # Setup arduino CLI
      
      - name: Setup Arduino CLI
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, matrix.test) }}
        uses: arduino/setup-arduino-cli@master

      # Configure platform
      # Arduino Nano Every with new CPU platform name is arduino:megaavr:nona4809:mode=off
      
      - name: Configure platform
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, matrix.test) }}
        run: |
          arduino-cli config init 
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core install arduino:megaavr
          arduino-cli lib install "DallasTemperature"
          
      # Compile
      
      - name: Compile sketch
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, matrix.test) }}
        run: |
          arduino-cli compile -b "arduino:megaavr:nona4809:mode=off" -e ./testers/${{ matrix.test }}