name: Check

on: [workflow_dispatch, push]

jobs:

  get-changed-files:
  
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.changedFiles.outputs.all_changed_files }}

    steps:

      # Clone repository
    
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Get changed files
        id: changedFiles
        uses: tj-actions/changed-files@v34.5.0

    # Compile code

  check:

    needs: get-changed-files

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

        tests: [ reed-switches ]
    

    runs-on: ${{ matrix.os }}
  
    steps:

      # Clone repository
      
      - name: Clone repository
        if: ${{ contains(needs.get-changed-files.outputs.output, matrix.tests) }}
        uses: actions/checkout@v3

      # Setup arduino CLI
      
      - name: Setup Arduino CLI
        if: ${{ contains(needs.get-changed-files.outputs.output, matrix.tests) }}
        uses: arduino/setup-arduino-cli@v1

      # Configure platform
      
      - name: Configure platform
        if: ${{ contains(needs.get-changed-files.outputs.output, matrix.tests) }}
        run: |
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          
      # Compile
      
      - name: Compile sketch
        if: ${{ contains(needs.get-changed-files.outputs.output, matrix.tests) }}
        run: |
          arduino-cli compile -b "esp8266:esp8266:nodemcuv2" -e ./testers/${{ matrix.tests }}