name: Check compilation

on: [workflow_dispatch, push]

jobs:

  checkChanges:
  
    runs-on: ubuntu-latest

    outputs:
        output1: steps.checkChanges.outputs.out

    steps:

      # Clone repository
    
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Get changed files
        uses: tj-actions/changed-files@v34.5.0


    # Compile code

  test:

    needs: checkChanges

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

        tests: [ reed-switches ]
    

    runs-on: ${{ matrix.os }}
  
    steps:

      # Clone repository
      
      - name: Clone repository
        if: steps.checkChanges.outputs.all_changed_files == ${{ matrix.tests }}
        uses: actions/checkout@v3

      # Setup arduino CLI
      
      - name: Setup Arduino CLI
        if: steps.checkChanges.outputs.all_changed_files == ${{ matrix.tests }}
        uses: arduino/setup-arduino-cli@v1

      # Configure platform
      
      - name: Configure platform
        if: steps.checkChanges.outputs.all_changed_files == ${{ matrix.tests }}
        run: |
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          
      # Compile
      
      - name: Compile sketch
        if: steps.checkChanges.outputs.all_changed_files == ${{ matrix.tests }}
        run: |
          arduino-cli compile -b "esp8266:esp8266:nodemcuv2" -e ./testers/${{ matrix.tests }}